//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSmsManager.Core {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenSmsManager.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device message storages could not be enumerated.
        /// </summary>
        internal static string DeviceMessageStoragesNotEnumeratedMsg {
            get {
                return ResourceManager.GetString("DeviceMessageStoragesNotEnumeratedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to start communication with device.
        /// </summary>
        internal static string FailedStartCommWithPhoneMsg {
            get {
                return ResourceManager.GetString("FailedStartCommWithPhoneMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid response after sending {0}, expected {1} but got {2}.
        /// </summary>
        internal static string InvalidResponseAfterSendingCommand {
            get {
                return ResourceManager.GetString("InvalidResponseAfterSendingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No response after sending {0}.
        /// </summary>
        internal static string NoResponseAfterSendingCommandMsg {
            get {
                return ResourceManager.GetString("NoResponseAfterSendingCommandMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only SMS-DELIVER messages can be decoded!.
        /// </summary>
        internal static string OnlySmsDeliverMessagesCanBeDecodedMsg {
            get {
                return ResourceManager.GetString("OnlySmsDeliverMessagesCanBeDecodedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sender.
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serial port is allready open..
        /// </summary>
        internal static string SerialPortOpenMsg {
            get {
                return ResourceManager.GetString("SerialPortOpenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Short Message Service Center.
        /// </summary>
        internal static string ShortMessageServiceCenter {
            get {
                return ResourceManager.GetString("ShortMessageServiceCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SmsMessage.
        /// </summary>
        internal static string SmsMessage {
            get {
                return ResourceManager.GetString("SmsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected response after sending AT command.
        /// </summary>
        internal static string UnexpectedResponseAfterSendingAtCommandMsg {
            get {
                return ResourceManager.GetString("UnexpectedResponseAfterSendingAtCommandMsg", resourceCulture);
            }
        }
    }
}
